# -*- coding: utf-8 -*-
# code generated by Prisma. DO NOT EDIT.
# pyright: reportUnusedImport=false
# fmt: off

# global imports for type checking
from builtins import bool as _bool
from builtins import int as _int
from builtins import float as _float
from builtins import str as _str
import sys
import decimal
import datetime
from typing import (
    TYPE_CHECKING,
    Optional,
    Iterable,
    Iterator,
    Sequence,
    Callable,
    ClassVar,
    NoReturn,
    TypeVar,
    Generic,
    Mapping,
    Tuple,
    Union,
    List,
    Dict,
    Type,
    Any,
    Set,
    overload,
    cast,
)
from typing_extensions import TypedDict, Literal


LiteralString = str
# -- template types.py.jinja --
from typing import TypeVar

import httpx
from . import _types
from .utils import _NoneType



# TODO: filters with aggregates should have their own recursive fields
# TODO: cleanup whitespace control
# TODO: add an argument to signify that the last iteration should be skipped


SortMode = _types.SortMode
SortOrder = _types.SortOrder

MetricsFormat = _types.MetricsFormat

DatasourceOverride = _types.DatasourceOverride
HttpConfig = _types.HttpConfig


# types that can be serialized to json by our query builder
Serializable = Union[
    None,
    bool,
    float,
    int,
    str,
    datetime.datetime,
    List[Any],
    Dict[None, Any],
    Dict[bool, Any],
    Dict[float, Any],
    Dict[int, Any],
    Dict[str, Any],
]


    

StringFilter = TypedDict(
    'StringFilter',
    {
        'equals': str,
        'not_in': List[str],
        'lt': str,
        'lte': str,
        'gt': str,
        'gte': str,
        'contains': str,
        'startswith': str,
        'endswith': str,
        'in': List[str],
        'not': Union[str, 'StringFilterRecursive1'],
        'mode': SortMode,
        'search': str,
    },
    total=False,
)


StringFilterRecursive1 = TypedDict(
    'StringFilterRecursive1',
    {
        'equals': str,
        'not_in': List[str],
        'lt': str,
        'lte': str,
        'gt': str,
        'gte': str,
        'contains': str,
        'startswith': str,
        'endswith': str,
        'in': List[str],
        'not': Union[str, 'StringFilterRecursive2'],
        'mode': SortMode,
        'search': str,
    },
    total=False,
)


StringFilterRecursive2 = TypedDict(
    'StringFilterRecursive2',
    {
        'equals': str,
        'not_in': List[str],
        'lt': str,
        'lte': str,
        'gt': str,
        'gte': str,
        'contains': str,
        'startswith': str,
        'endswith': str,
        'in': List[str],
        'not': Union[str, 'StringFilterRecursive3'],
        'mode': SortMode,
        'search': str,
    },
    total=False,
)


StringFilterRecursive3 = TypedDict(
    'StringFilterRecursive3',
    {
        'equals': str,
        'not_in': List[str],
        'lt': str,
        'lte': str,
        'gt': str,
        'gte': str,
        'contains': str,
        'startswith': str,
        'endswith': str,
        'in': List[str],
        'not': Union[str, 'StringFilterRecursive4'],
        'mode': SortMode,
        'search': str,
    },
    total=False,
)


StringFilterRecursive4 = TypedDict(
    'StringFilterRecursive4',
    {
        'equals': str,
        'not_in': List[str],
        'lt': str,
        'lte': str,
        'gt': str,
        'gte': str,
        'contains': str,
        'startswith': str,
        'endswith': str,
        'in': List[str],
                'mode': SortMode,
        'search': str,
    },
    total=False,
)


class StringWithAggregatesFilter(StringFilter, total=False):
    _max: 'StringFilter'
    _min: 'StringFilter'
    _sum: 'StringFilter'
    _avg: 'StringFilter'
    _count: 'IntFilter'


    

DateTimeFilter = TypedDict(
    'DateTimeFilter',
    {
        'equals': datetime.datetime,
        'not_in': List[datetime.datetime],
        'lt': datetime.datetime,
        'lte': datetime.datetime,
        'gt': datetime.datetime,
        'gte': datetime.datetime,
        'in': List[datetime.datetime],
        'not': Union[datetime.datetime, 'DateTimeFilterRecursive1'],
    },
    total=False,
)


DateTimeFilterRecursive1 = TypedDict(
    'DateTimeFilterRecursive1',
    {
        'equals': datetime.datetime,
        'not_in': List[datetime.datetime],
        'lt': datetime.datetime,
        'lte': datetime.datetime,
        'gt': datetime.datetime,
        'gte': datetime.datetime,
        'in': List[datetime.datetime],
        'not': Union[datetime.datetime, 'DateTimeFilterRecursive2'],
    },
    total=False,
)


DateTimeFilterRecursive2 = TypedDict(
    'DateTimeFilterRecursive2',
    {
        'equals': datetime.datetime,
        'not_in': List[datetime.datetime],
        'lt': datetime.datetime,
        'lte': datetime.datetime,
        'gt': datetime.datetime,
        'gte': datetime.datetime,
        'in': List[datetime.datetime],
        'not': Union[datetime.datetime, 'DateTimeFilterRecursive3'],
    },
    total=False,
)


DateTimeFilterRecursive3 = TypedDict(
    'DateTimeFilterRecursive3',
    {
        'equals': datetime.datetime,
        'not_in': List[datetime.datetime],
        'lt': datetime.datetime,
        'lte': datetime.datetime,
        'gt': datetime.datetime,
        'gte': datetime.datetime,
        'in': List[datetime.datetime],
        'not': Union[datetime.datetime, 'DateTimeFilterRecursive4'],
    },
    total=False,
)


DateTimeFilterRecursive4 = TypedDict(
    'DateTimeFilterRecursive4',
    {
        'equals': datetime.datetime,
        'not_in': List[datetime.datetime],
        'lt': datetime.datetime,
        'lte': datetime.datetime,
        'gt': datetime.datetime,
        'gte': datetime.datetime,
        'in': List[datetime.datetime],
            },
    total=False,
)


class DateTimeWithAggregatesFilter(DateTimeFilter, total=False):
    _max: 'DateTimeFilter'
    _min: 'DateTimeFilter'
    _sum: 'DateTimeFilter'
    _avg: 'DateTimeFilter'
    _count: 'IntFilter'


    

BooleanFilter = TypedDict(
    'BooleanFilter',
    {
        'equals': bool,
        'not': Union[bool, 'BooleanFilterRecursive1'],
    },
    total=False,
)


BooleanFilterRecursive1 = TypedDict(
    'BooleanFilterRecursive1',
    {
        'equals': bool,
        'not': Union[bool, 'BooleanFilterRecursive2'],
    },
    total=False,
)


BooleanFilterRecursive2 = TypedDict(
    'BooleanFilterRecursive2',
    {
        'equals': bool,
        'not': Union[bool, 'BooleanFilterRecursive3'],
    },
    total=False,
)


BooleanFilterRecursive3 = TypedDict(
    'BooleanFilterRecursive3',
    {
        'equals': bool,
        'not': Union[bool, 'BooleanFilterRecursive4'],
    },
    total=False,
)


BooleanFilterRecursive4 = TypedDict(
    'BooleanFilterRecursive4',
    {
        'equals': bool,
            },
    total=False,
)


class BooleanWithAggregatesFilter(BooleanFilter, total=False):
    _max: 'BooleanFilter'
    _min: 'BooleanFilter'
    _sum: 'BooleanFilter'
    _avg: 'BooleanFilter'
    _count: 'IntFilter'


    

IntFilter = TypedDict(
    'IntFilter',
    {
        'equals': int,
        'not_in': List[int],
        'lt': int,
        'lte': int,
        'gt': int,
        'gte': int,
        'in': List[int],
        'not': Union[int, 'IntFilterRecursive1'],
    },
    total=False,
)


IntFilterRecursive1 = TypedDict(
    'IntFilterRecursive1',
    {
        'equals': int,
        'not_in': List[int],
        'lt': int,
        'lte': int,
        'gt': int,
        'gte': int,
        'in': List[int],
        'not': Union[int, 'IntFilterRecursive2'],
    },
    total=False,
)


IntFilterRecursive2 = TypedDict(
    'IntFilterRecursive2',
    {
        'equals': int,
        'not_in': List[int],
        'lt': int,
        'lte': int,
        'gt': int,
        'gte': int,
        'in': List[int],
        'not': Union[int, 'IntFilterRecursive3'],
    },
    total=False,
)


IntFilterRecursive3 = TypedDict(
    'IntFilterRecursive3',
    {
        'equals': int,
        'not_in': List[int],
        'lt': int,
        'lte': int,
        'gt': int,
        'gte': int,
        'in': List[int],
        'not': Union[int, 'IntFilterRecursive4'],
    },
    total=False,
)


IntFilterRecursive4 = TypedDict(
    'IntFilterRecursive4',
    {
        'equals': int,
        'not_in': List[int],
        'lt': int,
        'lte': int,
        'gt': int,
        'gte': int,
        'in': List[int],
            },
    total=False,
)


class IntWithAggregatesFilter(IntFilter, total=False):
    _max: 'IntFilter'
    _min: 'IntFilter'
    _sum: 'IntFilter'
    _avg: 'IntFilter'
    _count: 'IntFilter'


BigIntFilter = IntFilter
BigIntWithAggregatesFilter = IntWithAggregatesFilter
    

FloatFilter = TypedDict(
    'FloatFilter',
    {
        'equals': float,
        'not_in': List[float],
        'lt': float,
        'lte': float,
        'gt': float,
        'gte': float,
        'in': List[float],
        'not': Union[float, 'FloatFilterRecursive1'],
    },
    total=False,
)


FloatFilterRecursive1 = TypedDict(
    'FloatFilterRecursive1',
    {
        'equals': float,
        'not_in': List[float],
        'lt': float,
        'lte': float,
        'gt': float,
        'gte': float,
        'in': List[float],
        'not': Union[float, 'FloatFilterRecursive2'],
    },
    total=False,
)


FloatFilterRecursive2 = TypedDict(
    'FloatFilterRecursive2',
    {
        'equals': float,
        'not_in': List[float],
        'lt': float,
        'lte': float,
        'gt': float,
        'gte': float,
        'in': List[float],
        'not': Union[float, 'FloatFilterRecursive3'],
    },
    total=False,
)


FloatFilterRecursive3 = TypedDict(
    'FloatFilterRecursive3',
    {
        'equals': float,
        'not_in': List[float],
        'lt': float,
        'lte': float,
        'gt': float,
        'gte': float,
        'in': List[float],
        'not': Union[float, 'FloatFilterRecursive4'],
    },
    total=False,
)


FloatFilterRecursive4 = TypedDict(
    'FloatFilterRecursive4',
    {
        'equals': float,
        'not_in': List[float],
        'lt': float,
        'lte': float,
        'gt': float,
        'gte': float,
        'in': List[float],
            },
    total=False,
)


class FloatWithAggregatesFilter(FloatFilter, total=False):
    _max: 'FloatFilter'
    _min: 'FloatFilter'
    _sum: 'FloatFilter'
    _avg: 'FloatFilter'
    _count: 'IntFilter'


    

BytesFilter = TypedDict(
    'BytesFilter',
    {
        'equals': 'fields.Base64',
        'in': List['fields.Base64'],
        'not_in': List['fields.Base64'],
        'not': Union['fields.Base64', 'BytesFilterRecursive1'],
    },
    total=False,
)


BytesFilterRecursive1 = TypedDict(
    'BytesFilterRecursive1',
    {
        'equals': 'fields.Base64',
        'in': List['fields.Base64'],
        'not_in': List['fields.Base64'],
        'not': Union['fields.Base64', 'BytesFilterRecursive2'],
    },
    total=False,
)


BytesFilterRecursive2 = TypedDict(
    'BytesFilterRecursive2',
    {
        'equals': 'fields.Base64',
        'in': List['fields.Base64'],
        'not_in': List['fields.Base64'],
        'not': Union['fields.Base64', 'BytesFilterRecursive3'],
    },
    total=False,
)


BytesFilterRecursive3 = TypedDict(
    'BytesFilterRecursive3',
    {
        'equals': 'fields.Base64',
        'in': List['fields.Base64'],
        'not_in': List['fields.Base64'],
        'not': Union['fields.Base64', 'BytesFilterRecursive4'],
    },
    total=False,
)


BytesFilterRecursive4 = TypedDict(
    'BytesFilterRecursive4',
    {
        'equals': 'fields.Base64',
        'in': List['fields.Base64'],
        'not_in': List['fields.Base64'],
            },
    total=False,
)


class BytesWithAggregatesFilter(BytesFilter, total=False):
    _max: 'BytesFilter'
    _min: 'BytesFilter'
    _sum: 'BytesFilter'
    _avg: 'BytesFilter'
    _count: 'IntFilter'


# TODO: preview feature for improving JSON filtering
JsonFilter = TypedDict(
    'JsonFilter',
    {
        'equals': 'fields.Json',
        'not': 'fields.Json',
    },
    total=False,
)


class JsonWithAggregatesFilter(JsonFilter, total=False):
    _max: 'JsonFilter'
    _min: 'JsonFilter'
    _sum: 'JsonFilter'
    _avg: 'JsonFilter'
    _count: 'IntFilter'


    

DecimalFilter = TypedDict(
    'DecimalFilter',
    {
        'equals': decimal.Decimal,
        'not_in': List[decimal.Decimal],
        'lt': decimal.Decimal,
        'lte': decimal.Decimal,
        'gt': decimal.Decimal,
        'gte': decimal.Decimal,
        'in': List[decimal.Decimal],
        'not': Union[decimal.Decimal, 'DecimalFilterRecursive1'],
    },
    total=False,
)


DecimalFilterRecursive1 = TypedDict(
    'DecimalFilterRecursive1',
    {
        'equals': decimal.Decimal,
        'not_in': List[decimal.Decimal],
        'lt': decimal.Decimal,
        'lte': decimal.Decimal,
        'gt': decimal.Decimal,
        'gte': decimal.Decimal,
        'in': List[decimal.Decimal],
        'not': Union[decimal.Decimal, 'DecimalFilterRecursive2'],
    },
    total=False,
)


DecimalFilterRecursive2 = TypedDict(
    'DecimalFilterRecursive2',
    {
        'equals': decimal.Decimal,
        'not_in': List[decimal.Decimal],
        'lt': decimal.Decimal,
        'lte': decimal.Decimal,
        'gt': decimal.Decimal,
        'gte': decimal.Decimal,
        'in': List[decimal.Decimal],
        'not': Union[decimal.Decimal, 'DecimalFilterRecursive3'],
    },
    total=False,
)


DecimalFilterRecursive3 = TypedDict(
    'DecimalFilterRecursive3',
    {
        'equals': decimal.Decimal,
        'not_in': List[decimal.Decimal],
        'lt': decimal.Decimal,
        'lte': decimal.Decimal,
        'gt': decimal.Decimal,
        'gte': decimal.Decimal,
        'in': List[decimal.Decimal],
        'not': Union[decimal.Decimal, 'DecimalFilterRecursive4'],
    },
    total=False,
)


DecimalFilterRecursive4 = TypedDict(
    'DecimalFilterRecursive4',
    {
        'equals': decimal.Decimal,
        'not_in': List[decimal.Decimal],
        'lt': decimal.Decimal,
        'lte': decimal.Decimal,
        'gt': decimal.Decimal,
        'gte': decimal.Decimal,
        'in': List[decimal.Decimal],
            },
    total=False,
)


class DecimalWithAggregatesFilter(StringFilter, total=False):
    _max: 'DecimalFilter'
    _min: 'DecimalFilter'
    _sum: 'DecimalFilter'
    _avg: 'DecimalFilter'
    _count: 'IntFilter'


class _FloatSetInput(TypedDict):
    set: float


class _FloatDivideInput(TypedDict):
    divide: float


class _FloatMultiplyInput(TypedDict):
    multiply: float


class _FloatIncrementInput(TypedDict):
    increment: float


class _FloatDecrementInput(TypedDict):
    decrement: float


class _IntSetInput(TypedDict):
    set: int


class _IntDivideInput(TypedDict):
    divide: int


class _IntMultiplyInput(TypedDict):
    multiply: int


class _IntIncrementInput(TypedDict):
    increment: int


class _IntDecrementInput(TypedDict):
    decrement: int


AtomicFloatInput = Union[
    _FloatSetInput,
    _FloatDivideInput,
    _FloatMultiplyInput,
    _FloatIncrementInput,
    _FloatDecrementInput,
]
AtomicIntInput = Union[
    _IntSetInput,
    _IntDivideInput,
    _IntMultiplyInput,
    _IntIncrementInput,
    _IntDecrementInput,
]
AtomicBigIntInput = AtomicIntInput

class _StringListFilterEqualsInput(TypedDict):
    equals: Optional[List[_str]]


class _StringListFilterHasInput(TypedDict):
    has: _str


class _StringListFilterHasEveryInput(TypedDict):
    has_every: List[_str]


class _StringListFilterHasSomeInput(TypedDict):
    has_some: List[_str]


class _StringListFilterIsEmptyInput(TypedDict):
    is_empty: bool


StringListFilter = Union[
    _StringListFilterHasInput,
    _StringListFilterEqualsInput,
    _StringListFilterHasSomeInput,
    _StringListFilterIsEmptyInput,
    _StringListFilterHasEveryInput,
]


class _StringListUpdateSet(TypedDict):
    set: List[_str]


class _StringListUpdatePush(TypedDict):
    push: List[_str]


StringListUpdate = Union[
    List[_str],
    _StringListUpdateSet,
    _StringListUpdatePush,
]

class _BytesListFilterEqualsInput(TypedDict):
    equals: Optional[List['fields.Base64']]


class _BytesListFilterHasInput(TypedDict):
    has: 'fields.Base64'


class _BytesListFilterHasEveryInput(TypedDict):
    has_every: List['fields.Base64']


class _BytesListFilterHasSomeInput(TypedDict):
    has_some: List['fields.Base64']


class _BytesListFilterIsEmptyInput(TypedDict):
    is_empty: bool


BytesListFilter = Union[
    _BytesListFilterHasInput,
    _BytesListFilterEqualsInput,
    _BytesListFilterHasSomeInput,
    _BytesListFilterIsEmptyInput,
    _BytesListFilterHasEveryInput,
]


class _BytesListUpdateSet(TypedDict):
    set: List['fields.Base64']


class _BytesListUpdatePush(TypedDict):
    push: List['fields.Base64']


BytesListUpdate = Union[
    List['fields.Base64'],
    _BytesListUpdateSet,
    _BytesListUpdatePush,
]

class _DateTimeListFilterEqualsInput(TypedDict):
    equals: Optional[List[datetime.datetime]]


class _DateTimeListFilterHasInput(TypedDict):
    has: datetime.datetime


class _DateTimeListFilterHasEveryInput(TypedDict):
    has_every: List[datetime.datetime]


class _DateTimeListFilterHasSomeInput(TypedDict):
    has_some: List[datetime.datetime]


class _DateTimeListFilterIsEmptyInput(TypedDict):
    is_empty: bool


DateTimeListFilter = Union[
    _DateTimeListFilterHasInput,
    _DateTimeListFilterEqualsInput,
    _DateTimeListFilterHasSomeInput,
    _DateTimeListFilterIsEmptyInput,
    _DateTimeListFilterHasEveryInput,
]


class _DateTimeListUpdateSet(TypedDict):
    set: List[datetime.datetime]


class _DateTimeListUpdatePush(TypedDict):
    push: List[datetime.datetime]


DateTimeListUpdate = Union[
    List[datetime.datetime],
    _DateTimeListUpdateSet,
    _DateTimeListUpdatePush,
]

class _BooleanListFilterEqualsInput(TypedDict):
    equals: Optional[List[_bool]]


class _BooleanListFilterHasInput(TypedDict):
    has: _bool


class _BooleanListFilterHasEveryInput(TypedDict):
    has_every: List[_bool]


class _BooleanListFilterHasSomeInput(TypedDict):
    has_some: List[_bool]


class _BooleanListFilterIsEmptyInput(TypedDict):
    is_empty: bool


BooleanListFilter = Union[
    _BooleanListFilterHasInput,
    _BooleanListFilterEqualsInput,
    _BooleanListFilterHasSomeInput,
    _BooleanListFilterIsEmptyInput,
    _BooleanListFilterHasEveryInput,
]


class _BooleanListUpdateSet(TypedDict):
    set: List[_bool]


class _BooleanListUpdatePush(TypedDict):
    push: List[_bool]


BooleanListUpdate = Union[
    List[_bool],
    _BooleanListUpdateSet,
    _BooleanListUpdatePush,
]

class _IntListFilterEqualsInput(TypedDict):
    equals: Optional[List[_int]]


class _IntListFilterHasInput(TypedDict):
    has: _int


class _IntListFilterHasEveryInput(TypedDict):
    has_every: List[_int]


class _IntListFilterHasSomeInput(TypedDict):
    has_some: List[_int]


class _IntListFilterIsEmptyInput(TypedDict):
    is_empty: bool


IntListFilter = Union[
    _IntListFilterHasInput,
    _IntListFilterEqualsInput,
    _IntListFilterHasSomeInput,
    _IntListFilterIsEmptyInput,
    _IntListFilterHasEveryInput,
]


class _IntListUpdateSet(TypedDict):
    set: List[_int]


class _IntListUpdatePush(TypedDict):
    push: List[_int]


IntListUpdate = Union[
    List[_int],
    _IntListUpdateSet,
    _IntListUpdatePush,
]

class _BigIntListFilterEqualsInput(TypedDict):
    equals: Optional[List[_int]]


class _BigIntListFilterHasInput(TypedDict):
    has: _int


class _BigIntListFilterHasEveryInput(TypedDict):
    has_every: List[_int]


class _BigIntListFilterHasSomeInput(TypedDict):
    has_some: List[_int]


class _BigIntListFilterIsEmptyInput(TypedDict):
    is_empty: bool


BigIntListFilter = Union[
    _BigIntListFilterHasInput,
    _BigIntListFilterEqualsInput,
    _BigIntListFilterHasSomeInput,
    _BigIntListFilterIsEmptyInput,
    _BigIntListFilterHasEveryInput,
]


class _BigIntListUpdateSet(TypedDict):
    set: List[_int]


class _BigIntListUpdatePush(TypedDict):
    push: List[_int]


BigIntListUpdate = Union[
    List[_int],
    _BigIntListUpdateSet,
    _BigIntListUpdatePush,
]

class _FloatListFilterEqualsInput(TypedDict):
    equals: Optional[List[_float]]


class _FloatListFilterHasInput(TypedDict):
    has: _float


class _FloatListFilterHasEveryInput(TypedDict):
    has_every: List[_float]


class _FloatListFilterHasSomeInput(TypedDict):
    has_some: List[_float]


class _FloatListFilterIsEmptyInput(TypedDict):
    is_empty: bool


FloatListFilter = Union[
    _FloatListFilterHasInput,
    _FloatListFilterEqualsInput,
    _FloatListFilterHasSomeInput,
    _FloatListFilterIsEmptyInput,
    _FloatListFilterHasEveryInput,
]


class _FloatListUpdateSet(TypedDict):
    set: List[_float]


class _FloatListUpdatePush(TypedDict):
    push: List[_float]


FloatListUpdate = Union[
    List[_float],
    _FloatListUpdateSet,
    _FloatListUpdatePush,
]

class _JsonListFilterEqualsInput(TypedDict):
    equals: Optional[List['fields.Json']]


class _JsonListFilterHasInput(TypedDict):
    has: 'fields.Json'


class _JsonListFilterHasEveryInput(TypedDict):
    has_every: List['fields.Json']


class _JsonListFilterHasSomeInput(TypedDict):
    has_some: List['fields.Json']


class _JsonListFilterIsEmptyInput(TypedDict):
    is_empty: bool


JsonListFilter = Union[
    _JsonListFilterHasInput,
    _JsonListFilterEqualsInput,
    _JsonListFilterHasSomeInput,
    _JsonListFilterIsEmptyInput,
    _JsonListFilterHasEveryInput,
]


class _JsonListUpdateSet(TypedDict):
    set: List['fields.Json']


class _JsonListUpdatePush(TypedDict):
    push: List['fields.Json']


JsonListUpdate = Union[
    List['fields.Json'],
    _JsonListUpdateSet,
    _JsonListUpdatePush,
]

class _DecimalListFilterEqualsInput(TypedDict):
    equals: Optional[List[decimal.Decimal]]


class _DecimalListFilterHasInput(TypedDict):
    has: decimal.Decimal


class _DecimalListFilterHasEveryInput(TypedDict):
    has_every: List[decimal.Decimal]


class _DecimalListFilterHasSomeInput(TypedDict):
    has_some: List[decimal.Decimal]


class _DecimalListFilterIsEmptyInput(TypedDict):
    is_empty: bool


DecimalListFilter = Union[
    _DecimalListFilterHasInput,
    _DecimalListFilterEqualsInput,
    _DecimalListFilterHasSomeInput,
    _DecimalListFilterIsEmptyInput,
    _DecimalListFilterHasEveryInput,
]


class _DecimalListUpdateSet(TypedDict):
    set: List[decimal.Decimal]


class _DecimalListUpdatePush(TypedDict):
    push: List[decimal.Decimal]


DecimalListUpdate = Union[
    List[decimal.Decimal],
    _DecimalListUpdateSet,
    _DecimalListUpdatePush,
]


# User types

class UserOptionalCreateInput(TypedDict, total=False):
    """Optional arguments to the User create method"""
    id: _str
    createdAt: datetime.datetime
    updatedAt: datetime.datetime
    displayName: Optional[_str]
    spotifyRefreshToken: Optional[_str]
    dislikedSongs: 'SongCreateManyNestedWithoutRelationsInput'
    likedSongs: 'SongCreateManyNestedWithoutRelationsInput'


class UserCreateInput(UserOptionalCreateInput):
    """Required arguments to the User create method"""
    username: _str
    hashedPassword: _str


# TODO: remove this in favour of without explicit relations
# e.g. PostCreateWithoutAuthorInput

class UserOptionalCreateWithoutRelationsInput(TypedDict, total=False):
    """Optional arguments to the User create method, without relations"""
    id: _str
    createdAt: datetime.datetime
    updatedAt: datetime.datetime
    displayName: Optional[_str]
    spotifyRefreshToken: Optional[_str]


class UserCreateWithoutRelationsInput(UserOptionalCreateWithoutRelationsInput):
    """Required arguments to the User create method, without relations"""
    username: _str
    hashedPassword: _str

class UserConnectOrCreateWithoutRelationsInput(TypedDict):
    create: 'UserCreateWithoutRelationsInput'
    where: 'UserWhereUniqueInput'

class UserCreateNestedWithoutRelationsInput(TypedDict, total=False):
    create: 'UserCreateWithoutRelationsInput'
    connect: 'UserWhereUniqueInput'
    connect_or_create: 'UserConnectOrCreateWithoutRelationsInput'


class UserCreateManyNestedWithoutRelationsInput(TypedDict, total=False):
    create: Union['UserCreateWithoutRelationsInput', List['UserCreateWithoutRelationsInput']]
    connect: Union['UserWhereUniqueInput', List['UserWhereUniqueInput']]
    connect_or_create: Union['UserConnectOrCreateWithoutRelationsInput', List['UserConnectOrCreateWithoutRelationsInput']]

_UserWhereUnique_id_Input = TypedDict(
    '_UserWhereUnique_id_Input',
    {
        'id': '_str',
    },
    total=True
)

_UserWhereUnique_username_Input = TypedDict(
    '_UserWhereUnique_username_Input',
    {
        'username': '_str',
    },
    total=True
)

UserWhereUniqueInput = Union[
    '_UserWhereUnique_id_Input',
    '_UserWhereUnique_username_Input',
]


class UserUpdateInput(TypedDict, total=False):
    """Optional arguments for updating a record"""
    id: _str
    username: _str
    createdAt: datetime.datetime
    updatedAt: datetime.datetime
    hashedPassword: _str
    displayName: Optional[_str]
    spotifyRefreshToken: Optional[_str]
    dislikedSongs: 'SongUpdateManyWithoutRelationsInput'
    likedSongs: 'SongUpdateManyWithoutRelationsInput'


class UserUpdateManyMutationInput(TypedDict, total=False):
    """Arguments for updating many records"""
    id: _str
    username: _str
    createdAt: datetime.datetime
    updatedAt: datetime.datetime
    hashedPassword: _str
    displayName: Optional[_str]
    spotifyRefreshToken: Optional[_str]


class UserUpdateManyWithoutRelationsInput(TypedDict, total=False):
    create: List['UserCreateWithoutRelationsInput']
    connect: List['UserWhereUniqueInput']
    connect_or_create: List['UserConnectOrCreateWithoutRelationsInput']
    set: List['UserWhereUniqueInput']
    disconnect: List['UserWhereUniqueInput']
    delete: List['UserWhereUniqueInput']

    # TODO
    # update: List['UserUpdateWithWhereUniqueWithoutRelationsInput']
    # updateMany: List['UserUpdateManyWithWhereUniqueWithoutRelationsInput']
    # deleteMany: List['UserScalarWhereInput']
    # upsert: List['UserUpserteWithWhereUniqueWithoutRelationsInput']


class UserUpdateOneWithoutRelationsInput(TypedDict, total=False):
    create: 'UserCreateWithoutRelationsInput'
    connect: 'UserWhereUniqueInput'
    connect_or_create: 'UserConnectOrCreateWithoutRelationsInput'
    disconnect: bool
    delete: bool

    # TODO
    # update: 'UserUpdateInput'
    # upsert: 'UserUpsertWithoutRelationsInput'


class UserUpsertInput(TypedDict):
    create: 'UserCreateInput'
    update: 'UserUpdateInput'  # pyright: ignore[reportIncompatibleMethodOverride]


_User_id_OrderByInput = TypedDict(
    '_User_id_OrderByInput',
    {
        'id': 'SortOrder',
    },
    total=True
)

_User_username_OrderByInput = TypedDict(
    '_User_username_OrderByInput',
    {
        'username': 'SortOrder',
    },
    total=True
)

_User_createdAt_OrderByInput = TypedDict(
    '_User_createdAt_OrderByInput',
    {
        'createdAt': 'SortOrder',
    },
    total=True
)

_User_updatedAt_OrderByInput = TypedDict(
    '_User_updatedAt_OrderByInput',
    {
        'updatedAt': 'SortOrder',
    },
    total=True
)

_User_hashedPassword_OrderByInput = TypedDict(
    '_User_hashedPassword_OrderByInput',
    {
        'hashedPassword': 'SortOrder',
    },
    total=True
)

_User_displayName_OrderByInput = TypedDict(
    '_User_displayName_OrderByInput',
    {
        'displayName': 'SortOrder',
    },
    total=True
)

_User_spotifyRefreshToken_OrderByInput = TypedDict(
    '_User_spotifyRefreshToken_OrderByInput',
    {
        'spotifyRefreshToken': 'SortOrder',
    },
    total=True
)

_User_RelevanceInner = TypedDict(
    '_User_RelevanceInner',
    {
        'fields': 'List[UserScalarFieldKeys]',
        'search': 'str',
        'sort': 'SortOrder',
    },
    total=True
)

_User_RelevanceOrderByInput = TypedDict(
    '_User_RelevanceOrderByInput',
    {
        '_relevance': '_User_RelevanceInner',
    },
    total=True
)

UserOrderByInput = Union[
    '_User_id_OrderByInput',
    '_User_username_OrderByInput',
    '_User_createdAt_OrderByInput',
    '_User_updatedAt_OrderByInput',
    '_User_hashedPassword_OrderByInput',
    '_User_displayName_OrderByInput',
    '_User_spotifyRefreshToken_OrderByInput',
    '_User_RelevanceOrderByInput',
]



# recursive User types
# TODO: cleanup these types


# Dict[str, Any] is a mypy limitation
# see https://github.com/RobertCraigie/prisma-client-py/issues/45
# switch to pyright for improved types, see https://prisma-client-py.readthedocs.io/en/stable/reference/limitations/

UserRelationFilter = TypedDict(
    'UserRelationFilter',
    {
        'is': 'Dict[str, Any]',
        'is_not': 'Dict[str, Any]',
    },
    total=False,
)


class UserListRelationFilter(TypedDict, total=False):
    some: 'Dict[str, Any]'
    none: 'Dict[str, Any]'
    every: 'Dict[str, Any]'


class UserInclude(TypedDict, total=False):
    """User relational arguments"""
    dislikedSongs: Union[bool, 'FindManySongArgsFromUser']
    likedSongs: Union[bool, 'FindManySongArgsFromUser']


    

class UserIncludeFromUser(TypedDict, total=False):
    """Relational arguments for User"""
    dislikedSongs: Union[bool, 'FindManySongArgsFromUserRecursive1']
    likedSongs: Union[bool, 'FindManySongArgsFromUserRecursive1']


class UserIncludeFromUserRecursive1(TypedDict, total=False):
    """Relational arguments for User"""
    dislikedSongs: Union[bool, 'FindManySongArgsFromUserRecursive2']
    likedSongs: Union[bool, 'FindManySongArgsFromUserRecursive2']


class UserIncludeFromUserRecursive2(TypedDict, total=False):
    """Relational arguments for User"""
    dislikedSongs: Union[bool, 'FindManySongArgsFromUserRecursive3']
    likedSongs: Union[bool, 'FindManySongArgsFromUserRecursive3']


class UserIncludeFromUserRecursive3(TypedDict, total=False):
    """Relational arguments for User"""
    dislikedSongs: Union[bool, 'FindManySongArgsFromUserRecursive4']
    likedSongs: Union[bool, 'FindManySongArgsFromUserRecursive4']


class UserIncludeFromUserRecursive4(TypedDict, total=False):
    """Relational arguments for User"""

    

class UserArgsFromUser(TypedDict, total=False):
    """Arguments for User"""
    include: 'UserIncludeFromUserRecursive1'


class UserArgsFromUserRecursive1(TypedDict, total=False):
    """Arguments for User"""
    include: 'UserIncludeFromUserRecursive2'


class UserArgsFromUserRecursive2(TypedDict, total=False):
    """Arguments for User"""
    include: 'UserIncludeFromUserRecursive3'


class UserArgsFromUserRecursive3(TypedDict, total=False):
    """Arguments for User"""
    include: 'UserIncludeFromUserRecursive4'


class UserArgsFromUserRecursive4(TypedDict, total=False):
    """Arguments for User"""
    
    

class FindManyUserArgsFromUser(TypedDict, total=False):
    """Arguments for User"""
    take: int
    skip: int
    order_by: Union['UserOrderByInput', List['UserOrderByInput']]
    where: 'UserWhereInput'
    cursor: 'UserWhereUniqueInput'
    distinct: List['UserScalarFieldKeys']
    include: 'UserIncludeFromUserRecursive1'


class FindManyUserArgsFromUserRecursive1(TypedDict, total=False):
    """Arguments for User"""
    take: int
    skip: int
    order_by: Union['UserOrderByInput', List['UserOrderByInput']]
    where: 'UserWhereInput'
    cursor: 'UserWhereUniqueInput'
    distinct: List['UserScalarFieldKeys']
    include: 'UserIncludeFromUserRecursive2'


class FindManyUserArgsFromUserRecursive2(TypedDict, total=False):
    """Arguments for User"""
    take: int
    skip: int
    order_by: Union['UserOrderByInput', List['UserOrderByInput']]
    where: 'UserWhereInput'
    cursor: 'UserWhereUniqueInput'
    distinct: List['UserScalarFieldKeys']
    include: 'UserIncludeFromUserRecursive3'


class FindManyUserArgsFromUserRecursive3(TypedDict, total=False):
    """Arguments for User"""
    take: int
    skip: int
    order_by: Union['UserOrderByInput', List['UserOrderByInput']]
    where: 'UserWhereInput'
    cursor: 'UserWhereUniqueInput'
    distinct: List['UserScalarFieldKeys']
    include: 'UserIncludeFromUserRecursive4'


class FindManyUserArgsFromUserRecursive4(TypedDict, total=False):
    """Arguments for User"""
    take: int
    skip: int
    order_by: Union['UserOrderByInput', List['UserOrderByInput']]
    where: 'UserWhereInput'
    cursor: 'UserWhereUniqueInput'
    distinct: List['UserScalarFieldKeys']
    
    

class SongIncludeFromUser(TypedDict, total=False):
    """Relational arguments for User"""
    dislikedBy: Union[bool, 'FindManyUserArgsFromUserRecursive1']
    likedBy: Union[bool, 'FindManyUserArgsFromUserRecursive1']


class SongIncludeFromUserRecursive1(TypedDict, total=False):
    """Relational arguments for User"""
    dislikedBy: Union[bool, 'FindManyUserArgsFromUserRecursive2']
    likedBy: Union[bool, 'FindManyUserArgsFromUserRecursive2']


class SongIncludeFromUserRecursive2(TypedDict, total=False):
    """Relational arguments for User"""
    dislikedBy: Union[bool, 'FindManyUserArgsFromUserRecursive3']
    likedBy: Union[bool, 'FindManyUserArgsFromUserRecursive3']


class SongIncludeFromUserRecursive3(TypedDict, total=False):
    """Relational arguments for User"""
    dislikedBy: Union[bool, 'FindManyUserArgsFromUserRecursive4']
    likedBy: Union[bool, 'FindManyUserArgsFromUserRecursive4']


class SongIncludeFromUserRecursive4(TypedDict, total=False):
    """Relational arguments for User"""

    

class SongArgsFromUser(TypedDict, total=False):
    """Arguments for User"""
    include: 'SongIncludeFromSongRecursive1'


class SongArgsFromUserRecursive1(TypedDict, total=False):
    """Arguments for User"""
    include: 'SongIncludeFromSongRecursive2'


class SongArgsFromUserRecursive2(TypedDict, total=False):
    """Arguments for User"""
    include: 'SongIncludeFromSongRecursive3'


class SongArgsFromUserRecursive3(TypedDict, total=False):
    """Arguments for User"""
    include: 'SongIncludeFromSongRecursive4'


class SongArgsFromUserRecursive4(TypedDict, total=False):
    """Arguments for User"""
    
    

class FindManySongArgsFromUser(TypedDict, total=False):
    """Arguments for User"""
    take: int
    skip: int
    order_by: Union['SongOrderByInput', List['SongOrderByInput']]
    where: 'SongWhereInput'
    cursor: 'SongWhereUniqueInput'
    distinct: List['SongScalarFieldKeys']
    include: 'SongIncludeFromSongRecursive1'


class FindManySongArgsFromUserRecursive1(TypedDict, total=False):
    """Arguments for User"""
    take: int
    skip: int
    order_by: Union['SongOrderByInput', List['SongOrderByInput']]
    where: 'SongWhereInput'
    cursor: 'SongWhereUniqueInput'
    distinct: List['SongScalarFieldKeys']
    include: 'SongIncludeFromSongRecursive2'


class FindManySongArgsFromUserRecursive2(TypedDict, total=False):
    """Arguments for User"""
    take: int
    skip: int
    order_by: Union['SongOrderByInput', List['SongOrderByInput']]
    where: 'SongWhereInput'
    cursor: 'SongWhereUniqueInput'
    distinct: List['SongScalarFieldKeys']
    include: 'SongIncludeFromSongRecursive3'


class FindManySongArgsFromUserRecursive3(TypedDict, total=False):
    """Arguments for User"""
    take: int
    skip: int
    order_by: Union['SongOrderByInput', List['SongOrderByInput']]
    where: 'SongWhereInput'
    cursor: 'SongWhereUniqueInput'
    distinct: List['SongScalarFieldKeys']
    include: 'SongIncludeFromSongRecursive4'


class FindManySongArgsFromUserRecursive4(TypedDict, total=False):
    """Arguments for User"""
    take: int
    skip: int
    order_by: Union['SongOrderByInput', List['SongOrderByInput']]
    where: 'SongWhereInput'
    cursor: 'SongWhereUniqueInput'
    distinct: List['SongScalarFieldKeys']
    


FindManyUserArgs = FindManyUserArgsFromUser
FindFirstUserArgs = FindManyUserArgsFromUser


    

class UserWhereInput(TypedDict, total=False):
    """User arguments for searching"""
    id: Union[_str, 'types.StringFilter']
    username: Union[_str, 'types.StringFilter']
    createdAt: Union[datetime.datetime, 'types.DateTimeFilter']
    updatedAt: Union[datetime.datetime, 'types.DateTimeFilter']
    hashedPassword: Union[_str, 'types.StringFilter']
    displayName: Union[None, _str, 'types.StringFilter']
    spotifyRefreshToken: Union[None, _str, 'types.StringFilter']
    dislikedSongs: 'SongListRelationFilter'
    likedSongs: 'SongListRelationFilter'

    # should be noted that AND and NOT should be Union['UserWhereInputRecursive1', List['UserWhereInputRecursive1']]
    # but this causes mypy to hang :/
    AND: List['UserWhereInputRecursive1']
    OR: List['UserWhereInputRecursive1']
    NOT: List['UserWhereInputRecursive1']


class UserWhereInputRecursive1(TypedDict, total=False):
    """User arguments for searching"""
    id: Union[_str, 'types.StringFilter']
    username: Union[_str, 'types.StringFilter']
    createdAt: Union[datetime.datetime, 'types.DateTimeFilter']
    updatedAt: Union[datetime.datetime, 'types.DateTimeFilter']
    hashedPassword: Union[_str, 'types.StringFilter']
    displayName: Union[None, _str, 'types.StringFilter']
    spotifyRefreshToken: Union[None, _str, 'types.StringFilter']
    dislikedSongs: 'SongListRelationFilter'
    likedSongs: 'SongListRelationFilter'

    # should be noted that AND and NOT should be Union['UserWhereInputRecursive2', List['UserWhereInputRecursive2']]
    # but this causes mypy to hang :/
    AND: List['UserWhereInputRecursive2']
    OR: List['UserWhereInputRecursive2']
    NOT: List['UserWhereInputRecursive2']


class UserWhereInputRecursive2(TypedDict, total=False):
    """User arguments for searching"""
    id: Union[_str, 'types.StringFilter']
    username: Union[_str, 'types.StringFilter']
    createdAt: Union[datetime.datetime, 'types.DateTimeFilter']
    updatedAt: Union[datetime.datetime, 'types.DateTimeFilter']
    hashedPassword: Union[_str, 'types.StringFilter']
    displayName: Union[None, _str, 'types.StringFilter']
    spotifyRefreshToken: Union[None, _str, 'types.StringFilter']
    dislikedSongs: 'SongListRelationFilter'
    likedSongs: 'SongListRelationFilter'

    # should be noted that AND and NOT should be Union['UserWhereInputRecursive3', List['UserWhereInputRecursive3']]
    # but this causes mypy to hang :/
    AND: List['UserWhereInputRecursive3']
    OR: List['UserWhereInputRecursive3']
    NOT: List['UserWhereInputRecursive3']


class UserWhereInputRecursive3(TypedDict, total=False):
    """User arguments for searching"""
    id: Union[_str, 'types.StringFilter']
    username: Union[_str, 'types.StringFilter']
    createdAt: Union[datetime.datetime, 'types.DateTimeFilter']
    updatedAt: Union[datetime.datetime, 'types.DateTimeFilter']
    hashedPassword: Union[_str, 'types.StringFilter']
    displayName: Union[None, _str, 'types.StringFilter']
    spotifyRefreshToken: Union[None, _str, 'types.StringFilter']
    dislikedSongs: 'SongListRelationFilter'
    likedSongs: 'SongListRelationFilter'

    # should be noted that AND and NOT should be Union['UserWhereInputRecursive4', List['UserWhereInputRecursive4']]
    # but this causes mypy to hang :/
    AND: List['UserWhereInputRecursive4']
    OR: List['UserWhereInputRecursive4']
    NOT: List['UserWhereInputRecursive4']


class UserWhereInputRecursive4(TypedDict, total=False):
    """User arguments for searching"""
    id: Union[_str, 'types.StringFilter']
    username: Union[_str, 'types.StringFilter']
    createdAt: Union[datetime.datetime, 'types.DateTimeFilter']
    updatedAt: Union[datetime.datetime, 'types.DateTimeFilter']
    hashedPassword: Union[_str, 'types.StringFilter']
    displayName: Union[None, _str, 'types.StringFilter']
    spotifyRefreshToken: Union[None, _str, 'types.StringFilter']
    dislikedSongs: 'SongListRelationFilter'
    likedSongs: 'SongListRelationFilter'



# aggregate User types


    

class UserScalarWhereWithAggregatesInput(TypedDict, total=False):
    """User arguments for searching"""
    id: Union[_str, 'types.StringWithAggregatesFilter']
    username: Union[_str, 'types.StringWithAggregatesFilter']
    createdAt: Union[datetime.datetime, 'types.DateTimeWithAggregatesFilter']
    updatedAt: Union[datetime.datetime, 'types.DateTimeWithAggregatesFilter']
    hashedPassword: Union[_str, 'types.StringWithAggregatesFilter']
    displayName: Union[_str, 'types.StringWithAggregatesFilter']
    spotifyRefreshToken: Union[_str, 'types.StringWithAggregatesFilter']

    AND: List['UserScalarWhereWithAggregatesInputRecursive1']
    OR: List['UserScalarWhereWithAggregatesInputRecursive1']
    NOT: List['UserScalarWhereWithAggregatesInputRecursive1']


class UserScalarWhereWithAggregatesInputRecursive1(TypedDict, total=False):
    """User arguments for searching"""
    id: Union[_str, 'types.StringWithAggregatesFilter']
    username: Union[_str, 'types.StringWithAggregatesFilter']
    createdAt: Union[datetime.datetime, 'types.DateTimeWithAggregatesFilter']
    updatedAt: Union[datetime.datetime, 'types.DateTimeWithAggregatesFilter']
    hashedPassword: Union[_str, 'types.StringWithAggregatesFilter']
    displayName: Union[_str, 'types.StringWithAggregatesFilter']
    spotifyRefreshToken: Union[_str, 'types.StringWithAggregatesFilter']

    AND: List['UserScalarWhereWithAggregatesInputRecursive2']
    OR: List['UserScalarWhereWithAggregatesInputRecursive2']
    NOT: List['UserScalarWhereWithAggregatesInputRecursive2']


class UserScalarWhereWithAggregatesInputRecursive2(TypedDict, total=False):
    """User arguments for searching"""
    id: Union[_str, 'types.StringWithAggregatesFilter']
    username: Union[_str, 'types.StringWithAggregatesFilter']
    createdAt: Union[datetime.datetime, 'types.DateTimeWithAggregatesFilter']
    updatedAt: Union[datetime.datetime, 'types.DateTimeWithAggregatesFilter']
    hashedPassword: Union[_str, 'types.StringWithAggregatesFilter']
    displayName: Union[_str, 'types.StringWithAggregatesFilter']
    spotifyRefreshToken: Union[_str, 'types.StringWithAggregatesFilter']

    AND: List['UserScalarWhereWithAggregatesInputRecursive3']
    OR: List['UserScalarWhereWithAggregatesInputRecursive3']
    NOT: List['UserScalarWhereWithAggregatesInputRecursive3']


class UserScalarWhereWithAggregatesInputRecursive3(TypedDict, total=False):
    """User arguments for searching"""
    id: Union[_str, 'types.StringWithAggregatesFilter']
    username: Union[_str, 'types.StringWithAggregatesFilter']
    createdAt: Union[datetime.datetime, 'types.DateTimeWithAggregatesFilter']
    updatedAt: Union[datetime.datetime, 'types.DateTimeWithAggregatesFilter']
    hashedPassword: Union[_str, 'types.StringWithAggregatesFilter']
    displayName: Union[_str, 'types.StringWithAggregatesFilter']
    spotifyRefreshToken: Union[_str, 'types.StringWithAggregatesFilter']

    AND: List['UserScalarWhereWithAggregatesInputRecursive4']
    OR: List['UserScalarWhereWithAggregatesInputRecursive4']
    NOT: List['UserScalarWhereWithAggregatesInputRecursive4']


class UserScalarWhereWithAggregatesInputRecursive4(TypedDict, total=False):
    """User arguments for searching"""
    id: Union[_str, 'types.StringWithAggregatesFilter']
    username: Union[_str, 'types.StringWithAggregatesFilter']
    createdAt: Union[datetime.datetime, 'types.DateTimeWithAggregatesFilter']
    updatedAt: Union[datetime.datetime, 'types.DateTimeWithAggregatesFilter']
    hashedPassword: Union[_str, 'types.StringWithAggregatesFilter']
    displayName: Union[_str, 'types.StringWithAggregatesFilter']
    spotifyRefreshToken: Union[_str, 'types.StringWithAggregatesFilter']



class UserGroupByOutput(TypedDict, total=False):
    id: _str
    username: _str
    createdAt: datetime.datetime
    updatedAt: datetime.datetime
    hashedPassword: _str
    displayName: _str
    spotifyRefreshToken: _str
    _sum: 'UserSumAggregateOutput'
    _avg: 'UserAvgAggregateOutput'
    _min: 'UserMinAggregateOutput'
    _max: 'UserMaxAggregateOutput'
    _count: 'UserCountAggregateOutput'


class UserAvgAggregateOutput(TypedDict, total=False):
    """User output for aggregating averages"""


class UserSumAggregateOutput(TypedDict, total=False):
    """User output for aggregating sums"""


class UserScalarAggregateOutput(TypedDict, total=False):
    """User output including scalar fields"""
    id: _str
    username: _str
    createdAt: datetime.datetime
    updatedAt: datetime.datetime
    hashedPassword: _str
    displayName: _str
    spotifyRefreshToken: _str


UserMinAggregateOutput = UserScalarAggregateOutput
UserMaxAggregateOutput = UserScalarAggregateOutput


class UserMaxAggregateInput(TypedDict, total=False):
    """User input for aggregating by max"""
    id: bool
    username: bool
    createdAt: bool
    updatedAt: bool
    hashedPassword: bool
    displayName: bool
    spotifyRefreshToken: bool


class UserMinAggregateInput(TypedDict, total=False):
    """User input for aggregating by min"""
    id: bool
    username: bool
    createdAt: bool
    updatedAt: bool
    hashedPassword: bool
    displayName: bool
    spotifyRefreshToken: bool


class UserNumberAggregateInput(TypedDict, total=False):
    """User input for aggregating numbers"""


UserAvgAggregateInput = UserNumberAggregateInput
UserSumAggregateInput = UserNumberAggregateInput


UserCountAggregateInput = TypedDict(
    'UserCountAggregateInput',
    {
        'id': bool,
        'username': bool,
        'createdAt': bool,
        'updatedAt': bool,
        'hashedPassword': bool,
        'displayName': bool,
        'spotifyRefreshToken': bool,
        '_all': bool,
    },
    total=False,
)

UserCountAggregateOutput = TypedDict(
    'UserCountAggregateOutput',
    {
        'id': int,
        'username': int,
        'createdAt': int,
        'updatedAt': int,
        'hashedPassword': int,
        'displayName': int,
        'spotifyRefreshToken': int,
        '_all': int,
    },
    total=False,
)


UserKeys = Literal[
    'id',
    'username',
    'createdAt',
    'updatedAt',
    'hashedPassword',
    'displayName',
    'spotifyRefreshToken',
    'dislikedSongs',
    'likedSongs',
]
UserScalarFieldKeys = Literal[
    'id',
    'username',
    'createdAt',
    'updatedAt',
    'hashedPassword',
    'displayName',
    'spotifyRefreshToken',
]
UserScalarFieldKeysT = TypeVar('UserScalarFieldKeysT', bound=UserScalarFieldKeys)

UserRelationalFieldKeys = Literal[
        'dislikedSongs',
        'likedSongs',
    ]

# Song types

class SongOptionalCreateInput(TypedDict, total=False):
    """Optional arguments to the Song create method"""
    id: _str
    mfccs: List[_float]
    dislikedBy: 'UserCreateManyNestedWithoutRelationsInput'
    likedBy: 'UserCreateManyNestedWithoutRelationsInput'


class SongCreateInput(SongOptionalCreateInput):
    """Required arguments to the Song create method"""
    spotify_id: _str
    title: _str
    album: _str
    recording_mbid: _str
    isrc: _str


# TODO: remove this in favour of without explicit relations
# e.g. PostCreateWithoutAuthorInput

class SongOptionalCreateWithoutRelationsInput(TypedDict, total=False):
    """Optional arguments to the Song create method, without relations"""
    id: _str
    mfccs: List[_float]


class SongCreateWithoutRelationsInput(SongOptionalCreateWithoutRelationsInput):
    """Required arguments to the Song create method, without relations"""
    spotify_id: _str
    title: _str
    album: _str
    recording_mbid: _str
    isrc: _str

class SongConnectOrCreateWithoutRelationsInput(TypedDict):
    create: 'SongCreateWithoutRelationsInput'
    where: 'SongWhereUniqueInput'

class SongCreateNestedWithoutRelationsInput(TypedDict, total=False):
    create: 'SongCreateWithoutRelationsInput'
    connect: 'SongWhereUniqueInput'
    connect_or_create: 'SongConnectOrCreateWithoutRelationsInput'


class SongCreateManyNestedWithoutRelationsInput(TypedDict, total=False):
    create: Union['SongCreateWithoutRelationsInput', List['SongCreateWithoutRelationsInput']]
    connect: Union['SongWhereUniqueInput', List['SongWhereUniqueInput']]
    connect_or_create: Union['SongConnectOrCreateWithoutRelationsInput', List['SongConnectOrCreateWithoutRelationsInput']]

_SongWhereUnique_id_Input = TypedDict(
    '_SongWhereUnique_id_Input',
    {
        'id': '_str',
    },
    total=True
)

_SongWhereUnique_spotify_id_Input = TypedDict(
    '_SongWhereUnique_spotify_id_Input',
    {
        'spotify_id': '_str',
    },
    total=True
)

_SongWhereUnique_recording_mbid_Input = TypedDict(
    '_SongWhereUnique_recording_mbid_Input',
    {
        'recording_mbid': '_str',
    },
    total=True
)

_SongWhereUnique_isrc_Input = TypedDict(
    '_SongWhereUnique_isrc_Input',
    {
        'isrc': '_str',
    },
    total=True
)

SongWhereUniqueInput = Union[
    '_SongWhereUnique_id_Input',
    '_SongWhereUnique_spotify_id_Input',
    '_SongWhereUnique_recording_mbid_Input',
    '_SongWhereUnique_isrc_Input',
]


class SongUpdateInput(TypedDict, total=False):
    """Optional arguments for updating a record"""
    id: _str
    spotify_id: _str
    title: _str
    album: _str
    recording_mbid: _str
    mfccs: 'types.FloatListUpdate'
    isrc: _str
    dislikedBy: 'UserUpdateManyWithoutRelationsInput'
    likedBy: 'UserUpdateManyWithoutRelationsInput'


class SongUpdateManyMutationInput(TypedDict, total=False):
    """Arguments for updating many records"""
    id: _str
    spotify_id: _str
    title: _str
    album: _str
    recording_mbid: _str
    mfccs: 'types.FloatListUpdate'
    isrc: _str


class SongUpdateManyWithoutRelationsInput(TypedDict, total=False):
    create: List['SongCreateWithoutRelationsInput']
    connect: List['SongWhereUniqueInput']
    connect_or_create: List['SongConnectOrCreateWithoutRelationsInput']
    set: List['SongWhereUniqueInput']
    disconnect: List['SongWhereUniqueInput']
    delete: List['SongWhereUniqueInput']

    # TODO
    # update: List['SongUpdateWithWhereUniqueWithoutRelationsInput']
    # updateMany: List['SongUpdateManyWithWhereUniqueWithoutRelationsInput']
    # deleteMany: List['SongScalarWhereInput']
    # upsert: List['SongUpserteWithWhereUniqueWithoutRelationsInput']


class SongUpdateOneWithoutRelationsInput(TypedDict, total=False):
    create: 'SongCreateWithoutRelationsInput'
    connect: 'SongWhereUniqueInput'
    connect_or_create: 'SongConnectOrCreateWithoutRelationsInput'
    disconnect: bool
    delete: bool

    # TODO
    # update: 'SongUpdateInput'
    # upsert: 'SongUpsertWithoutRelationsInput'


class SongUpsertInput(TypedDict):
    create: 'SongCreateInput'
    update: 'SongUpdateInput'  # pyright: ignore[reportIncompatibleMethodOverride]


_Song_id_OrderByInput = TypedDict(
    '_Song_id_OrderByInput',
    {
        'id': 'SortOrder',
    },
    total=True
)

_Song_spotify_id_OrderByInput = TypedDict(
    '_Song_spotify_id_OrderByInput',
    {
        'spotify_id': 'SortOrder',
    },
    total=True
)

_Song_title_OrderByInput = TypedDict(
    '_Song_title_OrderByInput',
    {
        'title': 'SortOrder',
    },
    total=True
)

_Song_album_OrderByInput = TypedDict(
    '_Song_album_OrderByInput',
    {
        'album': 'SortOrder',
    },
    total=True
)

_Song_recording_mbid_OrderByInput = TypedDict(
    '_Song_recording_mbid_OrderByInput',
    {
        'recording_mbid': 'SortOrder',
    },
    total=True
)

_Song_mfccs_OrderByInput = TypedDict(
    '_Song_mfccs_OrderByInput',
    {
        'mfccs': 'SortOrder',
    },
    total=True
)

_Song_isrc_OrderByInput = TypedDict(
    '_Song_isrc_OrderByInput',
    {
        'isrc': 'SortOrder',
    },
    total=True
)

_Song_RelevanceInner = TypedDict(
    '_Song_RelevanceInner',
    {
        'fields': 'List[SongScalarFieldKeys]',
        'search': 'str',
        'sort': 'SortOrder',
    },
    total=True
)

_Song_RelevanceOrderByInput = TypedDict(
    '_Song_RelevanceOrderByInput',
    {
        '_relevance': '_Song_RelevanceInner',
    },
    total=True
)

SongOrderByInput = Union[
    '_Song_id_OrderByInput',
    '_Song_spotify_id_OrderByInput',
    '_Song_title_OrderByInput',
    '_Song_album_OrderByInput',
    '_Song_recording_mbid_OrderByInput',
    '_Song_mfccs_OrderByInput',
    '_Song_isrc_OrderByInput',
    '_Song_RelevanceOrderByInput',
]



# recursive Song types
# TODO: cleanup these types


# Dict[str, Any] is a mypy limitation
# see https://github.com/RobertCraigie/prisma-client-py/issues/45
# switch to pyright for improved types, see https://prisma-client-py.readthedocs.io/en/stable/reference/limitations/

SongRelationFilter = TypedDict(
    'SongRelationFilter',
    {
        'is': 'Dict[str, Any]',
        'is_not': 'Dict[str, Any]',
    },
    total=False,
)


class SongListRelationFilter(TypedDict, total=False):
    some: 'Dict[str, Any]'
    none: 'Dict[str, Any]'
    every: 'Dict[str, Any]'


class SongInclude(TypedDict, total=False):
    """Song relational arguments"""
    dislikedBy: Union[bool, 'FindManyUserArgsFromSong']
    likedBy: Union[bool, 'FindManyUserArgsFromSong']


    

class UserIncludeFromSong(TypedDict, total=False):
    """Relational arguments for Song"""
    dislikedSongs: Union[bool, 'FindManySongArgsFromSongRecursive1']
    likedSongs: Union[bool, 'FindManySongArgsFromSongRecursive1']


class UserIncludeFromSongRecursive1(TypedDict, total=False):
    """Relational arguments for Song"""
    dislikedSongs: Union[bool, 'FindManySongArgsFromSongRecursive2']
    likedSongs: Union[bool, 'FindManySongArgsFromSongRecursive2']


class UserIncludeFromSongRecursive2(TypedDict, total=False):
    """Relational arguments for Song"""
    dislikedSongs: Union[bool, 'FindManySongArgsFromSongRecursive3']
    likedSongs: Union[bool, 'FindManySongArgsFromSongRecursive3']


class UserIncludeFromSongRecursive3(TypedDict, total=False):
    """Relational arguments for Song"""
    dislikedSongs: Union[bool, 'FindManySongArgsFromSongRecursive4']
    likedSongs: Union[bool, 'FindManySongArgsFromSongRecursive4']


class UserIncludeFromSongRecursive4(TypedDict, total=False):
    """Relational arguments for Song"""

    

class UserArgsFromSong(TypedDict, total=False):
    """Arguments for Song"""
    include: 'UserIncludeFromUserRecursive1'


class UserArgsFromSongRecursive1(TypedDict, total=False):
    """Arguments for Song"""
    include: 'UserIncludeFromUserRecursive2'


class UserArgsFromSongRecursive2(TypedDict, total=False):
    """Arguments for Song"""
    include: 'UserIncludeFromUserRecursive3'


class UserArgsFromSongRecursive3(TypedDict, total=False):
    """Arguments for Song"""
    include: 'UserIncludeFromUserRecursive4'


class UserArgsFromSongRecursive4(TypedDict, total=False):
    """Arguments for Song"""
    
    

class FindManyUserArgsFromSong(TypedDict, total=False):
    """Arguments for Song"""
    take: int
    skip: int
    order_by: Union['UserOrderByInput', List['UserOrderByInput']]
    where: 'UserWhereInput'
    cursor: 'UserWhereUniqueInput'
    distinct: List['UserScalarFieldKeys']
    include: 'UserIncludeFromUserRecursive1'


class FindManyUserArgsFromSongRecursive1(TypedDict, total=False):
    """Arguments for Song"""
    take: int
    skip: int
    order_by: Union['UserOrderByInput', List['UserOrderByInput']]
    where: 'UserWhereInput'
    cursor: 'UserWhereUniqueInput'
    distinct: List['UserScalarFieldKeys']
    include: 'UserIncludeFromUserRecursive2'


class FindManyUserArgsFromSongRecursive2(TypedDict, total=False):
    """Arguments for Song"""
    take: int
    skip: int
    order_by: Union['UserOrderByInput', List['UserOrderByInput']]
    where: 'UserWhereInput'
    cursor: 'UserWhereUniqueInput'
    distinct: List['UserScalarFieldKeys']
    include: 'UserIncludeFromUserRecursive3'


class FindManyUserArgsFromSongRecursive3(TypedDict, total=False):
    """Arguments for Song"""
    take: int
    skip: int
    order_by: Union['UserOrderByInput', List['UserOrderByInput']]
    where: 'UserWhereInput'
    cursor: 'UserWhereUniqueInput'
    distinct: List['UserScalarFieldKeys']
    include: 'UserIncludeFromUserRecursive4'


class FindManyUserArgsFromSongRecursive4(TypedDict, total=False):
    """Arguments for Song"""
    take: int
    skip: int
    order_by: Union['UserOrderByInput', List['UserOrderByInput']]
    where: 'UserWhereInput'
    cursor: 'UserWhereUniqueInput'
    distinct: List['UserScalarFieldKeys']
    
    

class SongIncludeFromSong(TypedDict, total=False):
    """Relational arguments for Song"""
    dislikedBy: Union[bool, 'FindManyUserArgsFromSongRecursive1']
    likedBy: Union[bool, 'FindManyUserArgsFromSongRecursive1']


class SongIncludeFromSongRecursive1(TypedDict, total=False):
    """Relational arguments for Song"""
    dislikedBy: Union[bool, 'FindManyUserArgsFromSongRecursive2']
    likedBy: Union[bool, 'FindManyUserArgsFromSongRecursive2']


class SongIncludeFromSongRecursive2(TypedDict, total=False):
    """Relational arguments for Song"""
    dislikedBy: Union[bool, 'FindManyUserArgsFromSongRecursive3']
    likedBy: Union[bool, 'FindManyUserArgsFromSongRecursive3']


class SongIncludeFromSongRecursive3(TypedDict, total=False):
    """Relational arguments for Song"""
    dislikedBy: Union[bool, 'FindManyUserArgsFromSongRecursive4']
    likedBy: Union[bool, 'FindManyUserArgsFromSongRecursive4']


class SongIncludeFromSongRecursive4(TypedDict, total=False):
    """Relational arguments for Song"""

    

class SongArgsFromSong(TypedDict, total=False):
    """Arguments for Song"""
    include: 'SongIncludeFromSongRecursive1'


class SongArgsFromSongRecursive1(TypedDict, total=False):
    """Arguments for Song"""
    include: 'SongIncludeFromSongRecursive2'


class SongArgsFromSongRecursive2(TypedDict, total=False):
    """Arguments for Song"""
    include: 'SongIncludeFromSongRecursive3'


class SongArgsFromSongRecursive3(TypedDict, total=False):
    """Arguments for Song"""
    include: 'SongIncludeFromSongRecursive4'


class SongArgsFromSongRecursive4(TypedDict, total=False):
    """Arguments for Song"""
    
    

class FindManySongArgsFromSong(TypedDict, total=False):
    """Arguments for Song"""
    take: int
    skip: int
    order_by: Union['SongOrderByInput', List['SongOrderByInput']]
    where: 'SongWhereInput'
    cursor: 'SongWhereUniqueInput'
    distinct: List['SongScalarFieldKeys']
    include: 'SongIncludeFromSongRecursive1'


class FindManySongArgsFromSongRecursive1(TypedDict, total=False):
    """Arguments for Song"""
    take: int
    skip: int
    order_by: Union['SongOrderByInput', List['SongOrderByInput']]
    where: 'SongWhereInput'
    cursor: 'SongWhereUniqueInput'
    distinct: List['SongScalarFieldKeys']
    include: 'SongIncludeFromSongRecursive2'


class FindManySongArgsFromSongRecursive2(TypedDict, total=False):
    """Arguments for Song"""
    take: int
    skip: int
    order_by: Union['SongOrderByInput', List['SongOrderByInput']]
    where: 'SongWhereInput'
    cursor: 'SongWhereUniqueInput'
    distinct: List['SongScalarFieldKeys']
    include: 'SongIncludeFromSongRecursive3'


class FindManySongArgsFromSongRecursive3(TypedDict, total=False):
    """Arguments for Song"""
    take: int
    skip: int
    order_by: Union['SongOrderByInput', List['SongOrderByInput']]
    where: 'SongWhereInput'
    cursor: 'SongWhereUniqueInput'
    distinct: List['SongScalarFieldKeys']
    include: 'SongIncludeFromSongRecursive4'


class FindManySongArgsFromSongRecursive4(TypedDict, total=False):
    """Arguments for Song"""
    take: int
    skip: int
    order_by: Union['SongOrderByInput', List['SongOrderByInput']]
    where: 'SongWhereInput'
    cursor: 'SongWhereUniqueInput'
    distinct: List['SongScalarFieldKeys']
    


FindManySongArgs = FindManySongArgsFromSong
FindFirstSongArgs = FindManySongArgsFromSong


    

class SongWhereInput(TypedDict, total=False):
    """Song arguments for searching"""
    id: Union[_str, 'types.StringFilter']
    spotify_id: Union[_str, 'types.StringFilter']
    title: Union[_str, 'types.StringFilter']
    album: Union[_str, 'types.StringFilter']
    recording_mbid: Union[_str, 'types.StringFilter']
    mfccs: 'types.FloatListFilter'
    isrc: Union[_str, 'types.StringFilter']
    dislikedBy: 'UserListRelationFilter'
    likedBy: 'UserListRelationFilter'

    # should be noted that AND and NOT should be Union['SongWhereInputRecursive1', List['SongWhereInputRecursive1']]
    # but this causes mypy to hang :/
    AND: List['SongWhereInputRecursive1']
    OR: List['SongWhereInputRecursive1']
    NOT: List['SongWhereInputRecursive1']


class SongWhereInputRecursive1(TypedDict, total=False):
    """Song arguments for searching"""
    id: Union[_str, 'types.StringFilter']
    spotify_id: Union[_str, 'types.StringFilter']
    title: Union[_str, 'types.StringFilter']
    album: Union[_str, 'types.StringFilter']
    recording_mbid: Union[_str, 'types.StringFilter']
    mfccs: 'types.FloatListFilter'
    isrc: Union[_str, 'types.StringFilter']
    dislikedBy: 'UserListRelationFilter'
    likedBy: 'UserListRelationFilter'

    # should be noted that AND and NOT should be Union['SongWhereInputRecursive2', List['SongWhereInputRecursive2']]
    # but this causes mypy to hang :/
    AND: List['SongWhereInputRecursive2']
    OR: List['SongWhereInputRecursive2']
    NOT: List['SongWhereInputRecursive2']


class SongWhereInputRecursive2(TypedDict, total=False):
    """Song arguments for searching"""
    id: Union[_str, 'types.StringFilter']
    spotify_id: Union[_str, 'types.StringFilter']
    title: Union[_str, 'types.StringFilter']
    album: Union[_str, 'types.StringFilter']
    recording_mbid: Union[_str, 'types.StringFilter']
    mfccs: 'types.FloatListFilter'
    isrc: Union[_str, 'types.StringFilter']
    dislikedBy: 'UserListRelationFilter'
    likedBy: 'UserListRelationFilter'

    # should be noted that AND and NOT should be Union['SongWhereInputRecursive3', List['SongWhereInputRecursive3']]
    # but this causes mypy to hang :/
    AND: List['SongWhereInputRecursive3']
    OR: List['SongWhereInputRecursive3']
    NOT: List['SongWhereInputRecursive3']


class SongWhereInputRecursive3(TypedDict, total=False):
    """Song arguments for searching"""
    id: Union[_str, 'types.StringFilter']
    spotify_id: Union[_str, 'types.StringFilter']
    title: Union[_str, 'types.StringFilter']
    album: Union[_str, 'types.StringFilter']
    recording_mbid: Union[_str, 'types.StringFilter']
    mfccs: 'types.FloatListFilter'
    isrc: Union[_str, 'types.StringFilter']
    dislikedBy: 'UserListRelationFilter'
    likedBy: 'UserListRelationFilter'

    # should be noted that AND and NOT should be Union['SongWhereInputRecursive4', List['SongWhereInputRecursive4']]
    # but this causes mypy to hang :/
    AND: List['SongWhereInputRecursive4']
    OR: List['SongWhereInputRecursive4']
    NOT: List['SongWhereInputRecursive4']


class SongWhereInputRecursive4(TypedDict, total=False):
    """Song arguments for searching"""
    id: Union[_str, 'types.StringFilter']
    spotify_id: Union[_str, 'types.StringFilter']
    title: Union[_str, 'types.StringFilter']
    album: Union[_str, 'types.StringFilter']
    recording_mbid: Union[_str, 'types.StringFilter']
    mfccs: 'types.FloatListFilter'
    isrc: Union[_str, 'types.StringFilter']
    dislikedBy: 'UserListRelationFilter'
    likedBy: 'UserListRelationFilter'



# aggregate Song types


    

class SongScalarWhereWithAggregatesInput(TypedDict, total=False):
    """Song arguments for searching"""
    id: Union[_str, 'types.StringWithAggregatesFilter']
    spotify_id: Union[_str, 'types.StringWithAggregatesFilter']
    title: Union[_str, 'types.StringWithAggregatesFilter']
    album: Union[_str, 'types.StringWithAggregatesFilter']
    recording_mbid: Union[_str, 'types.StringWithAggregatesFilter']
    mfccs: Union[_float, 'types.FloatWithAggregatesFilter']
    isrc: Union[_str, 'types.StringWithAggregatesFilter']

    AND: List['SongScalarWhereWithAggregatesInputRecursive1']
    OR: List['SongScalarWhereWithAggregatesInputRecursive1']
    NOT: List['SongScalarWhereWithAggregatesInputRecursive1']


class SongScalarWhereWithAggregatesInputRecursive1(TypedDict, total=False):
    """Song arguments for searching"""
    id: Union[_str, 'types.StringWithAggregatesFilter']
    spotify_id: Union[_str, 'types.StringWithAggregatesFilter']
    title: Union[_str, 'types.StringWithAggregatesFilter']
    album: Union[_str, 'types.StringWithAggregatesFilter']
    recording_mbid: Union[_str, 'types.StringWithAggregatesFilter']
    mfccs: Union[_float, 'types.FloatWithAggregatesFilter']
    isrc: Union[_str, 'types.StringWithAggregatesFilter']

    AND: List['SongScalarWhereWithAggregatesInputRecursive2']
    OR: List['SongScalarWhereWithAggregatesInputRecursive2']
    NOT: List['SongScalarWhereWithAggregatesInputRecursive2']


class SongScalarWhereWithAggregatesInputRecursive2(TypedDict, total=False):
    """Song arguments for searching"""
    id: Union[_str, 'types.StringWithAggregatesFilter']
    spotify_id: Union[_str, 'types.StringWithAggregatesFilter']
    title: Union[_str, 'types.StringWithAggregatesFilter']
    album: Union[_str, 'types.StringWithAggregatesFilter']
    recording_mbid: Union[_str, 'types.StringWithAggregatesFilter']
    mfccs: Union[_float, 'types.FloatWithAggregatesFilter']
    isrc: Union[_str, 'types.StringWithAggregatesFilter']

    AND: List['SongScalarWhereWithAggregatesInputRecursive3']
    OR: List['SongScalarWhereWithAggregatesInputRecursive3']
    NOT: List['SongScalarWhereWithAggregatesInputRecursive3']


class SongScalarWhereWithAggregatesInputRecursive3(TypedDict, total=False):
    """Song arguments for searching"""
    id: Union[_str, 'types.StringWithAggregatesFilter']
    spotify_id: Union[_str, 'types.StringWithAggregatesFilter']
    title: Union[_str, 'types.StringWithAggregatesFilter']
    album: Union[_str, 'types.StringWithAggregatesFilter']
    recording_mbid: Union[_str, 'types.StringWithAggregatesFilter']
    mfccs: Union[_float, 'types.FloatWithAggregatesFilter']
    isrc: Union[_str, 'types.StringWithAggregatesFilter']

    AND: List['SongScalarWhereWithAggregatesInputRecursive4']
    OR: List['SongScalarWhereWithAggregatesInputRecursive4']
    NOT: List['SongScalarWhereWithAggregatesInputRecursive4']


class SongScalarWhereWithAggregatesInputRecursive4(TypedDict, total=False):
    """Song arguments for searching"""
    id: Union[_str, 'types.StringWithAggregatesFilter']
    spotify_id: Union[_str, 'types.StringWithAggregatesFilter']
    title: Union[_str, 'types.StringWithAggregatesFilter']
    album: Union[_str, 'types.StringWithAggregatesFilter']
    recording_mbid: Union[_str, 'types.StringWithAggregatesFilter']
    mfccs: Union[_float, 'types.FloatWithAggregatesFilter']
    isrc: Union[_str, 'types.StringWithAggregatesFilter']



class SongGroupByOutput(TypedDict, total=False):
    id: _str
    spotify_id: _str
    title: _str
    album: _str
    recording_mbid: _str
    mfccs: List[_float]
    isrc: _str
    _sum: 'SongSumAggregateOutput'
    _avg: 'SongAvgAggregateOutput'
    _min: 'SongMinAggregateOutput'
    _max: 'SongMaxAggregateOutput'
    _count: 'SongCountAggregateOutput'


class SongAvgAggregateOutput(TypedDict, total=False):
    """Song output for aggregating averages"""
    mfccs: float


class SongSumAggregateOutput(TypedDict, total=False):
    """Song output for aggregating sums"""
    mfccs: List[_float]


class SongScalarAggregateOutput(TypedDict, total=False):
    """Song output including scalar fields"""
    id: _str
    spotify_id: _str
    title: _str
    album: _str
    recording_mbid: _str
    mfccs: List[_float]
    isrc: _str


SongMinAggregateOutput = SongScalarAggregateOutput
SongMaxAggregateOutput = SongScalarAggregateOutput


class SongMaxAggregateInput(TypedDict, total=False):
    """Song input for aggregating by max"""
    id: bool
    spotify_id: bool
    title: bool
    album: bool
    recording_mbid: bool
    mfccs: bool
    isrc: bool


class SongMinAggregateInput(TypedDict, total=False):
    """Song input for aggregating by min"""
    id: bool
    spotify_id: bool
    title: bool
    album: bool
    recording_mbid: bool
    mfccs: bool
    isrc: bool


class SongNumberAggregateInput(TypedDict, total=False):
    """Song input for aggregating numbers"""
    mfccs: bool


SongAvgAggregateInput = SongNumberAggregateInput
SongSumAggregateInput = SongNumberAggregateInput


SongCountAggregateInput = TypedDict(
    'SongCountAggregateInput',
    {
        'id': bool,
        'spotify_id': bool,
        'title': bool,
        'album': bool,
        'recording_mbid': bool,
        'mfccs': bool,
        'isrc': bool,
        '_all': bool,
    },
    total=False,
)

SongCountAggregateOutput = TypedDict(
    'SongCountAggregateOutput',
    {
        'id': int,
        'spotify_id': int,
        'title': int,
        'album': int,
        'recording_mbid': int,
        'mfccs': int,
        'isrc': int,
        '_all': int,
    },
    total=False,
)


SongKeys = Literal[
    'id',
    'spotify_id',
    'title',
    'album',
    'recording_mbid',
    'mfccs',
    'isrc',
    'dislikedBy',
    'likedBy',
]
SongScalarFieldKeys = Literal[
    'id',
    'spotify_id',
    'title',
    'album',
    'recording_mbid',
    'mfccs',
    'isrc',
]
SongScalarFieldKeysT = TypeVar('SongScalarFieldKeysT', bound=SongScalarFieldKeys)

SongRelationalFieldKeys = Literal[
        'dislikedBy',
        'likedBy',
    ]



# we have to import ourselves as types can be namespaced to types
from . import types, enums, models, fields